// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64

package embed

import _ "embed"

//go:embed assets/codex-feishu-relay-shim-darwin-amd64.zst
var embeddedShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "1c839b271d6acec15a7583ef4f56fb26943760b050a082ef1b50c43cd0475844",
		SHA256:       "9cb828d245cb0f17f5e5ea1b64bb969fab620971e47d12f05f4a971459243339",
		Zstd:         embeddedShim_darwin_amd64,
	})
}
